In [1]:
from sklearn.ensemble import GradientBoostingRegressorCV, GradientBoostingClassifierCV

from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier

from sklearn.datasets import load_boston, fetch_covtype, load_iris, make_classification
from sklearn.datasets import fetch_20newsgroups_vectorized, fetch_california_housing

from sklearn.model_selection import train_test_split, GridSearchCV

from time import time, sleep

import numpy as np

def memory_usage():
    """Memory usage of the current process in MBs."""
    status = None
    result = 0
    try:
        # This will only work on systems with a /proc file system
        # (like Linux).
        status = open('/proc/self/status')
        for line in status:
            parts = line.split()
            key = parts[0][2:-1].lower()
            if key == "rss":
                result = int(parts[1]) / 1024.0
    finally:
        if status is not None:
            status.close()
    return result

mkclf_dataset = make_classification(n_samples=1000000)
class make_clf_data:
    data = mkclf_dataset[0]
    target = mkclf_dataset[1]

FILENAME = "./bench_results"

n_samples = 1000000

# Let's load some datasets

datasets = {
    'boston': load_boston(),
    'covtype': fetch_covtype(),
    'iris': load_iris(),
    # 'twenty_ng': fetch_20newsgroups_vectorized(),
    'california_housing': fetch_california_housing(),
    'toy': make_clf_data(),
}

X, y = datasets['toy'].data[:10000, :], datasets['toy'].target[:10000]

In [2]:
gs_gbcv = GridSearchCV(GradientBoostingClassifier(random_state=0),
                       param_grid={'n_estimators': np.arange(1, 10)},
                       cv=5, n_jobs=8, )
gs_gbcv.fit(X, y)

import pandas as pd

res = pd.DataFrame(gs_gbcv.results_)
res.sort_values(by='test_rank_score')

param_n_estimators                params  test_mean_score  test_rank_score  \
6                  7  {u'n_estimators': 7}           0.9246                1   
7                  8  {u'n_estimators': 8}           0.9245                2   
5                  6  {u'n_estimators': 6}           0.9242                3   
4                  5  {u'n_estimators': 5}           0.9240                4   
3                  4  {u'n_estimators': 4}           0.9238                5   
8                  9  {u'n_estimators': 9}           0.9234                6   
2                  3  {u'n_estimators': 3}           0.9232                7   
1                  2  {u'n_estimators': 2}           0.9215                8   
0                  1  {u'n_estimators': 1}           0.9206                9   

   test_split0_score  test_split1_score  test_split2_score  test_split3_score  \
6           0.919040           0.925037             0.9220           0.922461   
7           0.916542           0.924038             0.9215           0.925963   
5           0.918041           0.924038             0.9215           0.922961   
4           0.919040           0.921039             0.9245           0.922961   
3           0.919040           0.921039             0.9245           0.921961   
8           0.917541           0.924038             0.9185           0.922461   
2           0.919040           0.921539             0.9255           0.922461   
1           0.919040           0.918041             0.9245           0.918959   
0           0.919540           0.918041             0.9230           0.915458   

   test_split4_score  test_std_score  
6           0.934467        0.005287  
7           0.934467        0.005899  
5           0.934467        0.005517  
4           0.932466        0.004612  
3           0.932466        0.004674  
8           0.934467        0.006034  
2           0.927464        0.002969  
1           0.926963        0.003558  
0           0.926963        0.004008

In [3]:
gbccv = GradientBoostingClassifierCV(max_iterations=10,
                                     n_stop_rounds=-1,
                                     cv=5, n_jobs=8,
                                     score_precision=40,
                                     random_state=0)
gbccv.fit(X, y)
gbccv.best_estimator_.n_estimators

We got 1 params
{'presort': 'auto', 'loss': 'deviance', 'subsample': 1.0, 'max_leaf_nodes': None, 'learning_rate': 0.10000000000000001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'init': None, 'min_weight_fraction_leaf': 0.0, 'max_features': None, 'max_depth': 3}
True
{'presort': 'auto', 'loss': 'deviance', 'subsample': 1.0, 'max_leaf_nodes': None, 'learning_rate': 0.10000000000000001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'init': None, 'min_weight_fraction_leaf': 0.0, 'max_features': None, 'max_depth': 3}
True
{'presort': 'auto', 'loss': 'deviance', 'subsample': 1.0, 'max_leaf_nodes': None, 'learning_rate': 0.10000000000000001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'init': None, 'min_weight_fraction_leaf': 0.0, 'max_features': None, 'max_depth': 3}
True
{'presort': 'auto', 'loss': 'deviance', 'subsample': 1.0, 'max_leaf_nodes': None, 'learning_rate': 0.10000000000000001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'init': None, 'min_weight_fraction_leaf': 0.0,

/tsi/doctorants/raghav/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/ensemble/gradient_boosting_cv.py:826: UserWarning: GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.10000000000000001, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=True) failed to converge
  warnings.warn(str(gb) + ' failed to converge')


2

In [11]:
a = np.arange(100)

a[-11:]

array([89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
gs_gbcv.results_

{'param_n_estimators': masked_array(data = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
  29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
  54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78
  79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99],
              mask = [False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False],
        fill_value = ?),
 

In [4]:
from sklearn.utils.testing import assert_almost_equal

print(gs_gbcv.best_estimator_.n_estimators)
print(gbccv.best_estimator_.n_estimators)

# assert_almost_equal(gs_gbcv.best_estimator_.predict_proba(X),
#                     gbccv.best_estimator_.predict_proba(X))

93
10


In [6]:
gbccv.best_estimator_.train_score_

array([ 1.23606116,  1.11309759,  1.00963735,  0.92220526,  0.84914598,
        0.78503404,  0.73146333,  0.6846948 ,  0.64285846,  0.60623699,
        0.5680244 ])

In [16]:
gs_gbcv.best_estimator_.train_score_

array([ 1.2524145 ,  1.14221217,  1.0503562 ,  0.97340518,  0.90841249,
        0.85226237,  0.80437878,  0.76312546,  0.72818248,  0.69712547,
        0.67054036,  0.64717796,  0.62685904,  0.60895972,  0.59271226,
        0.57864618,  0.56672179,  0.55382711,  0.54434467,  0.53538203,
        0.52587676,  0.51848051,  0.5125013 ,  0.50622393,  0.50089196,
        0.49507113,  0.49021927,  0.48499923,  0.48071931,  0.477123  ,
        0.47374711,  0.47006801,  0.46732341,  0.4649692 ,  0.46278586,
        0.45962777,  0.45717271,  0.45484543,  0.45339246,  0.45147373,
        0.45022306,  0.44863775,  0.44686975,  0.44560477])

In [11]:
from sklearn.metrics.scorer import check_scoring

gbccv.best_estimator_.score

<bound method GradientBoostingClassifier.score of GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.10000000000000001, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)>

In [ ]:
# Benchmark all of these on RegressionCV itself. (It can handle both continuous and non continuous data)

for n_jobs in [4, 8]:
    for name, dataset in datasets.items():
        X, y = dataset.data[:n_samples, :], dataset.target[:n_samples]
        with open(FILENAME, 'w+') as bench_results:
            bench_results.write("\n* %s dataset with %d samples, %d features run with n_jobs=%d"
                                % (name, X.shape[0], X.shape[1], n_jobs))
            print("\n* %s dataset with %d samples, %d features run with n_jobs=%d"
                  % (name, X.shape[0], X.shape[1], n_jobs))

        start = time()
        start_mem_usage = memory_usage()
        gbrcv = GradientBoostingRegressorCV(n_jobs=4, random_state=42)
        gbrcv.fit(X, y)
        end_mem_usage = memory_usage()
        end = time()
        
        with open(FILENAME, 'w+') as bench_results:
            bench_results.write(" took %0.2fs"
                                % (end - start,))# end_mem_usage - start_mem_usage))
        
        print(" took %0.2fs"
              % (end - start,))# end_mem_usage - start_mem_usage))


* boston dataset with 506 samples, 13 features run with n_jobs=4
 took 0.24s

* covtype dataset with 581012 samples, 54 features run with n_jobs=4


In [8]:
from sklearn.model_selection import ParameterGrid

params = {'presort': 'auto', 'loss': 'deviance',
          'subsample': 1.0, 'max_leaf_nodes': None,
          'learning_rate': 0.10000000000000001, 'min_samples_leaf': 1,
          'min_samples_split': 2, 'init': None, 'min_weight_fraction_leaf': 0.0,
          'max_features': None, 'max_depth': 3}

for key, value in params.items():
    params[key] = np.atleast_1d(value)

pg = ParameterGrid(params)
len(list(pg))

1

In [2]:
# With the threading

* boston dataset with 506 samples, 13 features run with n_jobs=4
 took 0.26s

* covtype dataset with 581012 samples, 54 features run with n_jobs=4
 took 110.35s

* california_housing dataset with 20640 samples, 8 features run with n_jobs=4
 took 3.30s

* toy dataset with 1000000 samples, 20 features run with n_jobs=4
 took 520.50s

* iris dataset with 150 samples, 4 features run with n_jobs=4
 took 0.15s

* boston dataset with 506 samples, 13 features run with n_jobs=8
 took 0.23s

* covtype dataset with 581012 samples, 54 features run with n_jobs=8
 took 108.83s

* california_housing dataset with 20640 samples, 8 features run with n_jobs=8
 took 3.20s

* toy dataset with 1000000 samples, 20 features run with n_jobs=8
 took 511.35s

* iris dataset with 150 samples, 4 features run with n_jobs=8
 took 0.14s
    
    
# Multiprocessing

* boston dataset with 506 samples, 13 features run with n_jobs=4
 took 0.31s

* covtype dataset with 581012 samples, 54 features run with n_jobs=4
 took 108.38s

* california_housing dataset with 20640 samples, 8 features run with n_jobs=4
 took 3.02s

* toy dataset with 1000000 samples, 20 features run with n_jobs=4
 took 445.69s

* iris dataset with 150 samples, 4 features run with n_jobs=4
 took 0.18s

* boston dataset with 506 samples, 13 features run with n_jobs=8
 took 0.31s

* covtype dataset with 581012 samples, 54 features run with n_jobs=8
 took 113.60s

* california_housing dataset with 20640 samples, 8 features run with n_jobs=8
 took 3.11s

* toy dataset with 1000000 samples, 20 features run with n_jobs=8
 took 457.10s

* iris dataset with 150 samples, 4 features run with n_jobs=8
 took 0.18s

In [3]:
X, y = covtype.data, covtype.target

gbc = GradientBoostingClassifierCV(n_jobs = 8)

print X.shape, y.shape

(581012, 54) (581012,)


In [ ]:
X, y = twenty_newsgroups.data, twenty_newsgroups.target

gbc = GradientBoostingClassifierCV(n_jobs=None)

In [ ]:
%%memit

# Dataset - Covtype full with shape - (581012, 54)
#
# * n_jobs = None
#     With multiprocessing - Used MB and took s
#     With threading - Used MB and took s
#
# * n_jobs = 4 (total available number of processors = 8)
#     With multiprocessing - (pre_dispatch = '1*n_jobs') - Used MB and took s
#     With threading - Used MB and took s
#
# * n_jobs = 8 (total available number of processors = 8)
#     With multiprocessing - (pre_dispatch = '1*n_jobs') - Used MB and took s
#     With threading - Used MB and took s
#

gbc.fit(X, y)

In [ ]:
%timeit

gbc.fit(X, y)

In [ ]:
print X.shape, y.shape